### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by MarcosCosmos** [rcorcs/SeqALib#1]
This is an interesting repository which could be useful for research - I'll note that the use of templates  may give the repository wider applicability than some others: there are some use cases for sequence alignment outside of bioinformatics, but the alphabet in such cases is not DNA bases and can be arbitrarily large.

However, it is unfortunately illegal to make use of your repository currently, as you have not licensed it (and therefore all rights are reserved).

If you would like to attach a license, GitHub offers some guidance: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by rcorcs** [comment]
Thanks for the interest and suggestion. An Apache 2.0 license has been added to the project.
